### PR TITLE
Upgrade to go 1.17

### PR DESCRIPTION
**Pull request by vicmarbev**
---
name: Pull request
about: Help us improve our package
title: "[WIP|Feature|Fix]"
labels: do-not-merge
assignees: johandry

---

**Community Note**

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Ensure you have added or ran the appropriate tests for this pull request
* If the PR is unfinished, add `[WIP]` prefix to the pull request title and add the `do-not-merge` label.
* Include in the title the category of this pull request. The categories are: `[WIP]`, `[Feature]` or `[Fix]`. If the category is unknown use `[WIP]`, once the PR is ready to be merged replace `[WIP]` for the right category.
* Always assign label(s) to your PR.

**What this PR does / Why we need it:**
Upgraded to Go 1.17 to take advantage of performance improvements.

**How I did it:**
Changed the version in go.mod and run go mod tidy.

**Description for the changelog:**
Upgraded to Go 1.17

### CODE REVIEW

**Comment by johandry** [comment]
Thanks!!

After running

```shell
❯ go version
go version go1.17.5 darwin/amd64
❯ export GOPATH=$(mktemp -d)
❯ go mod tidy
```

and got these versions in `go.mod` instead of yours:

```go
require (
// ...
	github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d // indirect
// ...
	golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586 // indirect
	golang.org/x/net v0.0.0-20191004110552-13f9640d40b9 // indirect
// ...
	golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456 // indirect
	golang.org/x/text v0.3.2 // indirect
// ...
)
```

Your versions - or some of them - are higher. I don't know why, could it be due to other dependencies in your environment?

**Comment by vicmarbev** [comment]
You are right! I've commited the changes, thanks.

**Review by johandry — APPROVED** [review]
LGTM

**Comment by vicmarbev** [comment]
Any comment about this?

**Pull request closed without merging**
